"""Add timestamp to Posts model

Revision ID: 124aee75a70b
Revises: 55a17c4e2771
Create Date: 2024-07-14 22:40:07.520112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124aee75a70b'
down_revision = '55a17c4e2771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
