"""Add photo column to posts

Revision ID: 24bba73c0a65
Revises: 4ea22c20fc83
Create Date: 2024-07-11 22:37:34.416462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bba73c0a65'
down_revision = '4ea22c20fc83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
