"""add date

Revision ID: 464911749648
Revises: 124aee75a70b
Create Date: 2024-07-14 23:15:50.832347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464911749648'
down_revision = '124aee75a70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
